name: agrilease
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_signin_button: ^2.0.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  pinput: ^2.2.12
  cloud_firestore: ^4.9.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true


  assets:
    - assets/images/agriculture.jpg
    - assets/images/logo.jpg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Comic
      fonts:
        #- asset: assets/fonts/ComicNeue-Bold.ttf
        #- asset: assets/fonts/Kanit-SemiBoldItalic.ttf
        - asset: assets/fonts/KaushanScript-Regular.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

